#!/usr/bin/env python
# -*- coding: utf-8 -*-
from datetime import *
from git import *
from gitroot import *
from ghname import *
from ghurl import *
from ospath import *

def run():
    dir = gitroot(__file__)
    path = unicode(dir)
    print("%s:" % path)
    print("")
    try:
        repo = Repo(path)
    except:
        repo = Repo.init(path)
    
    remotes = filter(
        lambda r:GHURL(r.url).github,
        repo.remotes
    )    
    if not remotes:
        #file = dir.join("name.txt")
        #if file.exists:
            #name = file.read()
        #else:
            #name = ghname(dir.basename)
        name = ghname(basename(unicode(dir)))
        remote = "github"
        ssh = unicode(GHURL(repo=name).ssh)
        r = repo.create_remote(remote,ssh)
        msg = "git remote add %s %s" % (remote,url)
        print(msg)
        repo.index.commit(msg)
    else:
        r = remotes[0]
        ssh = r.url
        if repo.is_dirty() or len(repo.untracked_files)>0:
            # changed
            msg = str(datetime.now())[:16]
            repo.git.add("-A")
            repo.index.commit(msg)
    branch = repo.heads.master
    print(ssh)
    r.push(branch)
    msg = "git push %s %s" % (r.name,branch.name)
    print(msg)
    print("")
    print(GHURL(ssh).html_url)

if __name__=="__main__":
    run()

