#!/bin/sh

img=$(find "$(git rev-parse --show-toplevel)" -name git-32.png ! -path .git)
cd "$(gitroot)"

branch=$(git branch | grep "*" | sed "s/* //")
for remote in `git remote`; do git push $remote $branch; done;

afplay /System/Library/Sounds/Glass.aiff 2> /dev/null
growlnotify -t "git push" -m "$(pwd)" --image "$img" 2> /dev/null

