#!/usr/bin/env python
# -*- coding: utf-8 -*-
from git import *
from gitroot import *
from ghname import *
from ghurl import *
from ospath import *

def run():
    dir = gitroot(__file__)
    file = dir.join("name.txt")
    if file.exists:
        name = file.read()
    else:
        name = ghname(dir.basename)

    path = unicode(dir)
    print("%s:" % path)
    print("")
    try:
        repo = Repo(path)
    except:
        repo = Repo.init(path)
        #repo.git.add('-A')

    remotes = filter(
        lambda r:GHURL(r.url).github,
        repo.remotes
    )
    if not remotes:
        remote = "github"
        url = unicode(GHURL(repo=name).ssh)
        r = repo.create_remote(remote,url)
        msg = "git remote add %s %s" % (remote,url)
        print(msg)
        repo.index.commit(msg)
    else:
        r = remotes[0]
        url = r.url

    print(url)

if __name__=="__main__":
    run()

