#!/usr/bin/env python
# -*- coding: utf-8 -*-
from os.path import *
from git import *
from gitroot import *
from gitconfig import *
from githubnotify import *
from githubrequests import *
from ghurl import *

user = gitconfig.user.name
remote = "github"

def run():
    global user, remote
    if not user:
        err = "user is empty"
        raise Exception(err)
    dir = gitroot(__file__)
    print("%s:" % dir)
    name = basename(dir)
    try:
        repo = Repo(dir)
    except:
        repo = Repo.init(dir)
    remotes = filter(
        lambda r:GHURL(r.url).github,
        repo.remotes
    )
    r = None
    if remotes:
        r = remotes[0]
        name = r.name
        url = r.url
        print(url)
        user = GHURL(url).user
    data = dict(name=name,user=user)
    print("")
    print("POST /user/repos")
    print(data)
    r = post("/user/repos",data)
    json = r.json()
    if not r and "ssh_url" in json:
        url = json["ssh_url"]
        repo.create_remote(remote,url)
        msg = "git remote add %s %s" % (remote,url)
        print(msg)
        repo.index.commit(msg)
    else:
        url = GHURL(user=user,repo=name).ssh
    # 201 ?
    if r.status_code in [200,422]:
        # 422 name already exists on this account
        print("")
        print(GHURL(url).html_url)
    else:
        print("")
        print("%s %s" % (r.status_code,json))
    
if __name__=="__main__":
    run()
